### ISSUE TITLE
Petaluma Public Water Connection

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#14]
There is a residential area northwest of Casa Grande Rd and southwest of Hidden Valley Dr. within the City of Petaluma, where many parcels are identified as NOT connected.  Oddly, they have a residential groundwater use of 0.0.  I don't know what is going on, but these parcels should be identified as having a public water connection.

Note, similar to Rohnert Park and City of Sonoma, all parcels within Petaluma are assumed to be connected.

**Comment by andyrich** [comment]
merge with issue #13

**Comment by andyrich** [comment]
duplicate of #13
