### ISSUE TITLE
Add other types of outdoor landscape, lawn and turf irrigation

### ISSUE THREAD

**Issue by andyrich** [andyrich/gfs_scwa#16]
When adding the 2012 land use data, it became clear that there are a number of land use types not covered by the schools and golf courses. There are cemeteries, parks, and various types of landscaping. 
See the following map:
https://andyrich.github.io/water_use/

**Comment by andyrich** [comment]
Add cemeteries, parks, and wineries. Don't change service connection status and impact to schema/labels.

**Comment by andyrich** [comment]
Add recycled water and surface uses to offset these groups.

**Comment by andyrich** [comment]
Changing the Use_Code_Description query to match any of the following:
**`school|golf|country club|winery|cemeter|city park|county park|privately owned park|business park common area`**

from the original:
**`school|golf|country club`**

**Comment by andyrich** [comment]
Here are the updated results of adding the above classes:
![image](https://user-images.githubusercontent.com/16653125/160475057-f0b0d128-8317-4051-b054-0d882df87f69.png)


And here are the new totals per basin and user group:
## updated
![image](https://user-images.githubusercontent.com/16653125/160475198-f070a030-563e-47cd-9ef0-442e6dca34ef.png)

## previous version
![image](https://user-images.githubusercontent.com/16653125/160475280-6e3d68fd-46b8-4e00-97c2-438b6bbbc068.png)

**Comment by andyrich** [comment]
Reminder - we select **parcels** based on their UseCode. We then do a spatial intersection of those parcels with 2012 Land Use data, which has the turf areas. Then based on that intersection we calculate the turf areas.

## **One Question**
I filtered the polygons with Recycled/reclaimed water from the land use, but did not filter polygons with surface water labeled as their source.

### The next logical quesions is: Should I either

_a) remove polygons with surface water sources as well?_

or 

_b) keep both polygons recycled water, surface water, and reclaimed water, and then let the records of recycled water/surface water availability/delivery establish whether there is sufficient alternate sources and therefore no groundwater usage?_

or 

_c) keep methods as they are_

**Comment by robertopennington** [comment]
I think the way you have done it is appropriate.   

One concern I have is that City Parks in Santa Rosa are accounted for in pumping data.  Can we account for that?  One option would be to use the "modified" fields for school and golf courses for the APNs within SR city limits.    

Similar to schools, we should probably do some targeted outreach for other city parks and rec areas as well.

**Comment by andyrich** [comment]
I'm going to close this issue without resolving "City Parks in Santa Rosa are accounted for in pumping data. Can we account for that? One option would be to use the "modified" fields for school and golf courses for the APNs within SR city limits." That can be accounted for in the modified columns if necessary.

**Comment by andyrich** [comment]
- [ ]  remove filter of parcel types that may have lawns -- ie any parcel use code description may have a lawn now
- [ ]  if a parcel has a public_well_conneciton == 'yes', then it must be greater than 0.5 acres in area to have a turf demand
- [ ]  if a parcel has a public_well_conneciton == 'no', then it must be greater than 0.2 acres in area to have a turf demand
