### ISSUE TITLE
Water Rights, POD

### ISSUE THREAD

**Issue by andyrich** [andyrich/gfs_scwa#24]
# Water rights currently do not capture points of diversion locations.
Currently only one location is associated with each Water Right - in somewhat rare instances, these locations may not coincide with any of the actual parcels associated with a water right. 

```
There are 265 water rights
There are 36 water rights with multiple points of diversions
There are 220 water rights with one points of diversions
```

For example, here is the ewrims for the 7550 Lakeville area:
![image](https://user-images.githubusercontent.com/16653125/161618726-e60a6ac5-b815-4c01-a9ec-df3a2452d945.png)

But here is how the current approach maps the same area (the black dots are the Water rights locations and the blue polygons are parcels with surface water rights as defined by the GSA database). It appears that the central location of the water right is actually located on top of a different parcel associated with an some kind of infrastructure, possibly an electric line:
![image](https://user-images.githubusercontent.com/16653125/161618814-c006378c-9ebd-45f9-bd0c-aef0b72fd23e.png)

Here are all of the water rights that are associated with multiple points of diversion:
![image](https://user-images.githubusercontent.com/16653125/161631864-5678f10e-6970-4d69-b8d2-1cf02ae61314.png)

![image](https://user-images.githubusercontent.com/16653125/161632612-0705aba4-0db1-4d5b-afdc-b4af2aa169b1.png)

['A030558', 'A029426', 'A029637', 'A031022', 'A029666', 'A031745', 'A029166', 'A032169', 'A031818', 'A028438', 'A030635', 'A031500', 'A030437', 'A028437', 'A030711', 'A021548', 'A031187', 'A030800', 'A027697', 'A026241', 'A031307', 'A013376', 'A013330', 'A030592', 'A029453', 'A026240', 'A031813', 'A022667', 'A020491', 'A029523', 'A020078', 'A024238', 'A028820', 'A013256', 'A012510', 'A009378']

**Comment by andyrich** [comment]
# proposed solution

- Spread the water right value amongst the POD locations associated with the water right, then apply proportionate use to overlaying parcel(s)? remove or edit PODs such as the one noted above that overlies incorrect parcel.

Solution will also need to account for the fact that a number of parcels (~63) are overlaid by water right locations, but these parcels do not show any surface water right usage in the database.

![image](https://user-images.githubusercontent.com/16653125/161639077-002b2185-af3a-4b21-a8a8-4e7530dbdeb4.png)

For some reason this appears only limited to Santa Rosa Plain:
![image](https://user-images.githubusercontent.com/16653125/161639169-3d6cb837-c928-43be-be3f-15f9133f7cc8.png)

**Comment by robertopennington** [comment]
What do you have in mind for "then apply proportionate use to overlaying parcel(s)".  Are you proposing to divide the FACE value by the number of parcels?

AS for SRP, is this a Raftellis carry over?  Do the omitted parcels with a surface water right have ag or turf GW uses?

**Comment by andyrich** [comment]
_What do you have in mind for "then apply proportionate use to overlaying parcel(s)". Are you proposing to divide the FACE value by the number of parcels? As in water right has FACE of 90 AFY with three parcels. Each parcel gets 30 AFY to offset uses._ 
#### that would be the approach. but i would also propose editing the locations of the POD's so that obvious POD outliers can be removed or moved to better parcels. maybe would use land use layer to identify parcels.

_AS for SRP, is this a Raftellis carry over? Do the omitted parcels with a surface water right have ag or turf GW uses?_
#### You are correct -- this looks like a Raftellis carry over. You can look at the parcels for SRP [here](https://andyrich.github.io/water_use/parcels_w_andwithout_PODs.html). But yes, many of them have GW demands, but because Raftellis data is used, none of these uses is offset.

# What do we do with the Raftellis Data?

**Comment by robertopennington** [comment]
What you propose sounds good.  For moving PODs, would you edit the POD point layer in GIS.  As for identifying the right parcel.  I think there can a be fair bit of info on each water right, including maps and application materials.  That seems like a good place to start.

As for SRP, if it is easy to do, clearing and replacing with the updated data for surface water rights seems appropriate if many of the parcels have high GW use.  Or identifying the APNs that were left out, and using the "modified fields"

**Comment by andyrich** [comment]
- [ ] Add Code to santa rosa plain to re-calculate surface water contributions
- [ ] Incorporate changes to GIS, namely 
- [ ] using edited POD's
- [ ] distributing surface water amongst various parcel(s) that may overlay all POD's

**Comment by andyrich** [comment]
# Reported total water used for all water rights

Inactive water rights are filtered out by removing water rights that have not reported any use between calendar year 2014 and 2021.

`Based on this analysis, we will use the average of the reported use from 2014 to 2021.`

![surface_water_divs NAPA-SONOMA VALLEY](https://user-images.githubusercontent.com/16653125/162268095-a3635f19-0e25-4857-b09c-e9964de42771.png)
![surface_water_divs SANTA ROSA VALLEY](https://user-images.githubusercontent.com/16653125/162268099-ca4b5283-1f7a-408b-9bcf-b7ef2a6c6455.png)
![surface_water_divs PETALUMA VALLEY](https://user-images.githubusercontent.com/16653125/162268101-db27af60-742e-4ebb-a624-e0aa9aa73f3a.png)

**Comment by andyrich** [comment]
```
From: Peter Kiel 
Sent: Wednesday, May 11, 2022 1:26 PM
To: Andrew Rich <Andrew.Rich@scwa.ca.gov>; Marcus Trotta <Marcus.Trotta@scwa.ca.gov>
Cc: Robert Pennington <Robert.Pennington@sonoma-county.org>; Jerry Bradshaw <jerry.bradshaw@sci-cg.com>; Ann DuBay <Ann.DuBay@scwa.ca.gov>
Subject: RE: Extraction Estimates

That database is the entire State database and sorting it takes some knowledge of the relevant watersheds (and more Excel skills than I have).  I sorted under the Petaluma and Tolay HUC 12 watersheds, but I am not sure I included everything relevant overlying this southeastern portion of the basin.  I may found a couple of extra rights not in your Word file.  Also, using the eWRIMS GIS map I found a few not more included in the Word file you sent.  This is not comprehensive and I may have missed some in this area with significant vineyard acreage.  My brief review of the Word diversions you sent shows that none of the Statements of Water Diversion and Use were included, and apparently some of the permits and licenses were omitted too.  I skipped stockponds in the database but I suspect some growers are using ponds permitted for stockwatering for crop irrigation as well.  In short I do not believe your surface water data fairly represents the surface water offset to estimated groundwater use.

Petaluma River watershed south/southeast of Frates Road 
 S022467  Oxfoot @ 30 AFA 87.7 acres of mixed crops
 S022936  Oxfoot  @35 AFA for 100 acres of vines plus stock
 S022317  Flocchini Estate - last 2.5 year avg use is @ 10 AFA for 29 acres of vines

Tolay Creek watershed
S019759  Universal Portfolio @30 AFA for 96 acres of vines
S019753 Universal Portfolio - @10 AFA for 36 acres of vines
 S019756  Universal Portfolio - @20 AFA for 96 acres of vines and 36 ac fruit trees
 A027898  Bliss Canyon @20+ AFA 68 acres vines and 5 acres of olives 

Sheetflow ponds are harder to document but I am personally aware of one @ 80 AF sheetflow pond on Browns Lan, and another that is @ 20-25 AF off Stage Gulch.  If I review my notes I might be able to document more of these.

I missed a 245 AF pond near Tolay Lake:  A029166  Oxfoot up to 245 AFA, 200 acres vines
```

**Comment by andyrich** [comment]
# Update water rights database using the recently pulled database
[water_rights_ewrims_export_all_sonoma_20220505.csv](https://github.com/andyrich/gfs_scwa/files/8703672/water_rights_ewrims_export_all_sonoma_20220505.csv)

as noted by peter kiel, the database used by LWA is missing a number of water rights. The new database has these water rights.
