### ISSUE TITLE
Urban Wells

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#25]
Develop strategy to add or remove urban wells.

Option:  From the current database, export a list of all urban wells and save as "Urban Wells List".  Update the code to read in "Urban Wells List", and assign APNs on this list a "Yes" and all others APNs a "No" for Urban Wells.   When an APN needs to be added or removed, just add or remove from the input file.

**Comment by andyrich** [comment]
That sounds reasonable. Do we want to remove the existing SRP data for this field after exporting list of `urban wells`? And then use new list to determine for all urban wells?

**Comment by robertopennington** [comment]
Yeah, the Petaluma Code is definitely problematic.  Though use of the well database is appealing.  Do you think it could be useful for identifying Urban Wells on parcels with Public Water Connection = "Yes"

I believe there is a short list of APNs from the City of Petaluma that identifies APNs with both a water connection and a private well.  I don't think they provided a list of backflow devices.  

For SRP, yes, I would propose setting Urban Well = "No" for all APNs, then overwriting with the newly created master list of Urban Wells. 

I find the use of backflow prevention devices to be problematic in general.  I think you agree. Perhaps filtering out the APNs with Use Codes we default to Water Connection "Yes" would make sense.   Any other ideas?

**Comment by robertopennington** [comment]
The "Private Wells" tab of "Petaluma CROSSCONNECT...." are urban wells.  Parcels with a well and a connection = "Yes"

I'm getting to the larger analysis of the Urban Wells now....

**Comment by robertopennington** [comment]
After analyzing and looking at the source data for Raftellis, I think it is worth keeping the Urban Wells.   The Santa Rosa data from the city seems to indicate that there is an onsite well.  That said, I would like to remove all the condos and small apartments.

I propose that I create a master list of Urban wells from the soco_gsas_parcel.csv.  I'll delete the condos and apartments and add the additional urban wells from Petaluma.  Then you can simply import the master list and overwrite the Urban Well data. Sound okay?
