### ISSUE TITLE
LandSizeAcres

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#33]
LandSizeAcres in the Schema is intended to represent the total area of the parcel.  The code makes this the area of the parcel that overlaps the basin.  

Propose:
1. Pull area from the parcel database and write to LandSizeAcres.
2. Make the area of the parcel that intersects the basin an intermediate variable that is not written to the output files.

**Comment by robertopennington** [comment]
There seems to be an issue for parcels along the boundary.  For boundary parcels,  LandSizeAcres  should be sell than LandSizeParcelAcres.  But other than that intersect two basins (SPR/PET),   LandSizeAcres = LandSizeParcelAcres

**Comment by robertopennington** [comment]
There is also a field Intersect_GSA_Bndry_Sum_Ac
Is this being used?  Sounds like a repeat of LandSize Acres (which was initially supposed to represent the parcel size)

**Comment by robertopennington** [comment]
Wait,  Intersect_GSA_Bndry_Sum_Ac was the combined area within a priority basin.  So not identical.

**Comment by andyrich** [comment]
solved via changes to schema
