### ISSUE TITLE
School Golf Modified Values

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#35]
Update the School Golf modified values to allow us to import a list of parcels with modified values (based off the info that Ann is getting)

#After this section of code
ppet <- ppet %>% 
  mutate(School_Golf_Modified       = "No",
         School_Golf_Modified_Ac_Ft = NA,
         School_Golf_GW_Use_Comment = NA,
         School_Golf_GW_Use_Ac_Ft = NA)

#Import the table (Does not exist yet, I will create this) with modified values and write to School_Golf_Modified, School_Golf_GW_Use_Modified_Ac_Ft and School_Golf_GW_Use_Comment 

#Then run something like below to update the  School_Golf_GW_Use_Ac_Ft , which stores the final value
 School_Golf_GW_Use_Ac_Ft = ifelse(School_Golf_Modified == "Yes", 
                                           School_Golf_GW_Use_Modified_Ac_Ft, 
                                           School_Golf_GW_Use_Prelim_Ac_Ft))

**Comment by andyrich** [comment]
We will use the following spreadsheets to import the modfied values:
![image](https://user-images.githubusercontent.com/16653125/165826703-a6c5885a-04e5-4226-8641-7b50d5083610.png)

They have the following structure:
![image](https://user-images.githubusercontent.com/16653125/165826893-42b0d87d-9355-4a27-b2b1-ea6ddf5d5f1b.png)

The tables will belong in the following folder:

general\modified_values

**Comment by andyrich** [comment]
- [ ] Need to move Petaluma Commercial pumping from the` Petaluma CROSSCONNECTION DATA CLEANED.xlsx` to the `Commercial_GW_Use_Modified` table. The code has been commented that pulled in the ` Petaluma CROSSCONNECTION DATA CLEANED.xlsx` , so the pumping will not show up unless the `Commercial_GW_Use_Modified` is updated.

**Comment by andyrich** [comment]
Tables have been uploaded to the shared website.
