### ISSUE TITLE
remove all turf irrigation from Rohnert Park

### ISSUE THREAD

**Issue by andyrich** [andyrich/gfs_scwa#49]
- [ ] remove all groundwater turf irrigation within the City of RP.

It seems we should remove all groundwater turf irrigation within the City of RP.

From: Pawson, Mary Grace <[mpawson@rpcity.org](mailto:mpawson@rpcity.org)> 
Sent: Monday, May 9, 2022 9:28 AM
To: Marcus Trotta <[Marcus.Trotta@scwa.ca.gov](mailto:Marcus.Trotta@scwa.ca.gov)>
Subject: RE: Non-City Groundwater Use within City of RP?

The school district does not have any wells….they were exploring the option a couple of years ago and we had to nix it. 

The golf courses use recycled water…we have a contractual allocation from subregional so there should not ever be a year where we don’t have recycled water available. If something really weird happens, we would need to supplement from the City system which, as you know, is a mix of Agency water and ground water. 

SSU also is a big user of recycled water for irrigation…they are included in our allocation from Subregional. If something really weird happens, they would be supplementing from their groundwater wells.

From: Marcus Trotta [mailto:Marcus.Trotta@scwa.ca.gov] 
Sent: Monday, May 9, 2022 9:25 AM
To: Pawson, Mary Grace <[mpawson@rpcity.org](mailto:mpawson@rpcity.org)>
Subject: Non-City Groundwater Use within City of RP?

EXTERNAL EMAIL
Hi Mary Grace – I’m wondering if you could confirm some assumptions for the rate and fee study for us regarding non-City GW pumping for turf irrigation within the City, as I know the City does not allow private wells within the City limits.

•	For all golf courses within the City, recycled water is used for turf irrigation, correct? 
o	If there are situations where sufficient recycled water is not available in a given year, do the courses use groundwater from their own irrigation wells to supplement?  Or do they supplement with the City’s potable supply (mix of aqueduct/groundwater)?
•	Do you know if any of the schools or other users use private groundwater wells for turf irrigation?

If possible to get back to me with any answers you have readily available sometime this morning, that would be greatly appreciated!

Thank you,

-Marcus

**Comment by robertopennington** [comment]
Easy, draft of modified turf parcels has been updated.

**Comment by andyrich** [comment]
![mod_valuesCommercial_GW_Use_Modified](https://user-images.githubusercontent.com/16653125/167493501-eca91e1e-e036-4df1-ace7-7726e89984d2.png)
![mod_valuesRes_GW_Use_Modified](https://user-images.githubusercontent.com/16653125/167493506-d1240036-a520-4be9-aa1b-b55c19cb330d.png)
![mod_valuesSchool_Golf_Modified](https://user-images.githubusercontent.com/16653125/167493508-648f35c4-3528-4ec6-9772-73f3cd47e606.png)
![mod_valuesAg_GW_Use_Modified](https://user-images.githubusercontent.com/16653125/167493510-22390c4d-1588-49d7-befd-7caa815bca1a.png)
![mod_valuesUrban_Irrigation_Modified](https://user-images.githubusercontent.com/16653125/167493511-c2be5ad6-3834-4778-9f3f-f14c3568bd3c.png)
