### ISSUE TITLE
Uploaded new School Golf Modified

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#50]
Latest and greatest was uploaded at 3:30 on 5_9_2022

**Comment by andyrich** [comment]
Thanks, it would be best to not open a new issue  - just re-open issue that this pertains to. Will be easier to track the issues. Not a big deal though.

**Comment by andyrich** [comment]
issue #49 issue #16

**Comment by robertopennington** [comment]
New versions of the selected files shown in the clip below were uploaded to the sharedrive on 6/16/2022

![image](https://user-images.githubusercontent.com/7247088/174146138-5cea5c98-174b-4576-a0f0-802a329c25fa.png)

**Comment by robertopennington** [comment]
Hi Andy, were all these checked files (other than Shared Well) brought into the updated database?

**Comment by andyrich** [comment]
Sorry I don’t think I did this

**Comment by robertopennington** [comment]
Hey Andy, how goes this?  I want to have Shelly update the GUIDE with the latest and greatest database, so please let me know once these modified files are included in a new uploaded database.

**Comment by andyrich** [comment]
The following files are not used in the code:
Shared_Well_Modified.xlsx and Connection_Status_Modified.xlsx

**Comment by andyrich** [comment]
There seem to be issues with your files:
The commercial use modified I have has 82 rows:
![image](https://user-images.githubusercontent.com/16653125/177691602-67eaf36e-c7af-44f1-b2f7-267d5f826848.png)

Your new one has only 7:
![image](https://user-images.githubusercontent.com/16653125/177691648-7cc6b1fc-99ef-46dd-97cf-0752be82038a.png)

Similarly the ag (my version):
![image](https://user-images.githubusercontent.com/16653125/177691750-ac1c4e7c-abfc-43ae-88e6-8bfe14bc28a8.png)

Your version:
![image](https://user-images.githubusercontent.com/16653125/177691779-e19185a7-8e1e-4fe8-aac0-90841fe74dc9.png)

**Comment by robertopennington** [comment]
Dang, looks like we have a versioning issue for ag and commercial modified lists.    Can you just append the lists and check/remove duplicates?  Then upload the updated versions to the share drive?

Why is "Connection_Status_Modified" not used in the code?  I thought you were updating to allow the "Yes" to "No" and vice versa.

**Comment by andyrich** [comment]
Oh, the "Connection_Status_modified" is actually the modified APN's? If so then yes that has been incorporated. Can you confirm that is correct?

**Comment by robertopennington** [comment]
Will you upload the appended modified Ag and Commercial layers to the sharedrive?

**Comment by andyrich** [comment]
The connection status modified was already uptodate as of 7/8/2022

**Comment by andyrich** [comment]
- [ ] updated commercial
- [ ] updated ag modifed
- [ ] updated Res_gw_use_modified
- [ ] updated school_golf_modified
- [ ] updated urban_irrigation (no changes, both empty)
- [ ] uploaded tables to PRMD portal
