### ISSUE TITLE
Connection Status Modified

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#62]
I analyzed the Sebastopol data, and added parcels to the "Connection Status Modified. XLSX" that should connection status set to "Yes" and other parcels where connection status should be set to "No".  

I've uploaded to the sharedrive on 5_31_2022 with name "Connection Status Modified"

Note, I deleted a file named "Modified APNs 2022_02_22" from the share drive .  Name that the R code searches for may need to be updated.

**Comment by andyrich** [comment]
The code was setup to only capture modified APN's with "yes" connections. Changing code to allow for "no".
