### ISSUE TITLE
Shared Well Modified

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#63]
From GUIDE surveys we get information that parcels use water from a shared well.  I created layer called "Shared_Well_Modified" that is uploaded to the share drive.  
First column is the parcel that receives water from a shared well. 
Second is APN of the well. 
Third column is comment

Code should be written to update values of fields for APN listed in the first column:
1.  Shared_Well = YES 
2.  Shared_Well_APN  =  APN listed in second column
3.  Wtr_Source_Comment  = append the text in third column

**Comment by andyrich** [comment]
These changes should wait until we have better plan of how incorporate GUIDE information into database. Also we need to figure out who will do that work.
