### ISSUE TITLE
School water use

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#7]
Develop alternative method for school water, and possibly golf course, groundwater use.  Zooming around to the various school properties, many are largely undeveloped and likely have very little water use.  Method using 2012 DWR should be discussed.

**Comment by andyrich** [comment]
# following meeting with Marcus, Rob, and Andy: schools with
         # a public water connection are assumed to NOT draw from groundwater
         School_Golf_GW_Use_Prelim_Ac_Ft = 
           ifelse(str_detect(tolower(UseCode_Description), "school") &
                    Public_Water_Connection == "Yes",
                  0, School_Golf_GW_Use_Prelim_Ac_Ft),
         # following meeting with Marcus, Rob, and Andy: golf courses with
         # NO onsite well(s) are assumed to NOT draw from groundwater
         School_Golf_GW_Use_Prelim_Ac_Ft = 
           ifelse(str_detect(tolower(UseCode_Description), "golf|country club") &
                    Onsite_Well == "No",
                  0, School_Golf_GW_Use_Prelim_Ac_Ft)

@robertopennington  do you agree with this?

**Comment by robertopennington** [comment]
I remember agreeing to the school logic, but have reservations about the assumption that schools served by public water are not using groundwater for irrigation.  

I don't agree with the golf or country club code, and don't remember agreeing to that.  The well database in incomplete and cannot be relied upon to determine if a parcel is or is not using groundwater

**Comment by andyrich** [comment]
I went ahead and implemented the changes noted below in yesterday’s email regarding schools and golf courses. 

Here are the totals before these changes. 
 
![image](https://user-images.githubusercontent.com/16653125/159805730-5d09709f-53e1-4488-9034-69318a1e8bae.png)


Here’s the new summaries, which also reflects the changes noted on the closed github issues preceding this one. The school/golf course changes are fairly significant
![image](https://user-images.githubusercontent.com/16653125/159805759-e175026d-3a62-482c-97b9-a8b3e49b42f9.png)

**Comment by robertopennington** [comment]
Thanks for doing this Andy!  
I wonder if we should add other Assessor Use Codes including *Cemetery*, *State Park*, and *County Park*?

**Comment by andyrich** [comment]
Check out this map of all the "UL" Urban landscape mapped by the 2012 data. These polygons are all irrigated (not by reclaimed/recycled water). The colored polygons are the 2012 Land Use data with specific class of UL. The dark grey polygons underneath are all of the school/golf course polygons. As you can see there are number of UL polygons not showing up in the Rate Study estimates.

https://andyrich.github.io/water_use/
