### ISSUE TITLE
city of sonoma connections 2023

### ISSUE THREAD

**Issue by andyrich** [andyrich/gfs_scwa#83]
Rob Pennington received updated connections from Oriana Hart around 5/12/2023.

Rob, should the following code be commented out now?

https://github.com/andyrich/gfs_scwa/blob/d2aeb249e6d4d8de95b2f334bfe6a1309aa2b913/code/03_son.R#L290-L303

**Comment by robertopennington** [comment]
An alternative would be to do a bit of preprocessing and recreate a list of all parcels that are connected to City of Sonoma, then import that list as I believe you were suggesting above.   That might be a bit cleaner and more understandable in the long run.
